package:
    type:           yii2-extension
    name:           yii2-hiart
    title:          Tools to use API as ActiveRecord for Yii2
    headline:       HiArt
    keywords:       api, ActiveRecord, extension, yii2
    namespace:      hiqdev\hiart
    description:    Use your API as ActiveRecord

