package:
    name:           yii2-hiart
    namespace:      hiqdev\hiart
    label:          HiArt
    title:          Tools to use API as ActiveRecord for Yii2
    type:           yii2-extension
    keywords:       api, ActiveRecord, extension, yii2
    description:    Grid DetailView: use grid/Columns for DetailView and more later
    year:           2015

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
